FROM node:lts

RUN useradd -m frontend || echo "User exists; skipping creation."
WORKDIR /home/frontend

COPY package*.json .
RUN npm install

COPY --chown=frontend:frontend . .
USER frontend

EXPOSE 3000
CMD ["npm", "start"]
