#######################################################################
### This file creates Docker containers for a MySQL database,       ###
### the Directus headless CMS, and the Python backend with Flask.   ###
#######################################################################
services:
  directus:
    image: directus/directus:latest
    ports:
      - "8055:8055"
    networks:
      - app
  
  flask:
    build:
      context: backend/
    ports:
    - "5000:5000"
    networks:
      - app

  mysql:
    image: mysql
    restart: always
    volumes:
       - ./data:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - app

networks:
  app:
    driver: bridge
