#######################################################################
### This file creates Docker containers for the backend with Flask  ###
### and the frontend with React.                                    ###
#######################################################################
services:
  flask:
    image: python:slim
    description: "Flask backend"
    volumes:
      - nszw:/var/lib/flask
    build:
      context: backend/
      dockerfile: dockerfile
    restart: always
    ports:
      - "5000:5000"
    networks:
      - app
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/api/hello"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  react:
    image: node:latest
    description: "React frontend"
    volumes:
      - nszw:/var/lib/react
    build:
      context: frontend/
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app
    depends_on:
      flask:
        condition: service_healthy


networks:
  app:
    driver: bridge
  

volumes:
  nszw:
  db:
    