#######################################################################
### This file creates Docker containers for a MySQL database,       ###
### the Directus headless CMS, and the Python backend with Flask.   ###
#######################################################################
services:
  # MySQL
  db:
    image: mysql
    container_name: db
    restart: always
    volumes:
      - ./data:/var/lib/mysql/
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DB}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    networks:
      - app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  
  # Python backend
  flask:
    container_name: app
    build:
      context: .
      dockerfile: dockerfile 
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition:
          service_healthy
    networks:
      - app
    command: python excel_migration.py

# Directus
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - "8055:8055"
    depends_on:
      db:
        condition: 
          service_healthy
    environment:
      DB_CLIENT: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: "${SQL_DB}"
      DB_USER: "${SQL_USER}"
      DB_PASSWORD: "${SQL_PASSWORD}"
    networks:
      - app

networks:
  app:
    driver:  bridge