<?php
 return [
  'name' => 'imprisonment',
  'label' => 'Gefangenschaft',
  'info' => '',
  'type' => 'collection',
  'fields' => [
    0 => [
      'name' => 'person',
      'type' => 'contentItemLink',
      'label' => 'Inhaftierte Person',
      'info' => '',
      'group' => 'Referenz',
      'i18n' => false,
      'required' => true,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'filter' => NULL,
        'link' => 'person',
        'display' => NULL,
      ],
    ],
    1 => [
      'name' => 'prisoner_id',
      'type' => 'number',
      'label' => 'Inhaftierten Nummer',
      'info' => '',
      'group' => 'Details',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
      ],
    ],
    2 => [
      'name' => 'from',
      'type' => 'date',
      'label' => 'Start der Inhaftnahme',
      'info' => '',
      'group' => 'Datum',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
      ],
    ],
    3 => [
      'name' => 'to',
      'type' => 'date',
      'label' => 'Ende der Inhaftnahme',
      'info' => '',
      'group' => 'Datum',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
      ],
    ],
    4 => [
      'name' => 'age_at_imprisonment',
      'type' => 'text',
      'label' => 'Alter an Inhaftierung',
      'info' => '',
      'group' => 'Details',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    5 => [
      'name' => 'prisoner_of_war',
      'type' => 'boolean',
      'label' => 'Kriegsgefangener',
      'info' => '',
      'group' => 'Details',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'label' => '',
        'mode' => 'boolean',
      ],
    ],
    6 => [
      'name' => 'court_of_law',
      'type' => 'text',
      'label' => 'Gerichtshof',
      'info' => '',
      'group' => 'Details',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    7 => [
      'name' => 'prison',
      'type' => 'contentItemLink',
      'label' => 'Gefängsnis',
      'info' => '',
      'group' => 'Referenz',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'link' => 'housing',
        'filter' => NULL,
        'display' => NULL,
      ],
    ],
  ],
  'preview' => [
  ],
  'group' => 'Gefangenschaft',
  'meta' => NULL,
  '_created' => 1764674179,
  '_modified' => 1764890326,
  'color' => NULL,
  'revisions' => false,
];