<?php
 return [
  'name' => 'person',
  'label' => 'Person',
  'info' => '',
  'type' => 'collection',
  'fields' => [
    0 => [
      'name' => 'surname',
      'type' => 'text',
      'label' => 'Nachname',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    1 => [
      'name' => 'name',
      'type' => 'text',
      'label' => 'Vorname',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    2 => [
      'name' => 'maiden_name',
      'type' => 'text',
      'label' => 'Gerburtsname',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    3 => [
      'name' => 'gender',
      'type' => 'select',
      'label' => 'Geschlecht',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'options' => [
          0 => 'M',
          1 => 'W',
          2 => 'D',
        ],
      ],
    ],
    4 => [
      'name' => 'place_of_birth',
      'type' => 'text',
      'label' => 'Geburtsort',
      'info' => '',
      'group' => 'Person_Ort',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    5 => [
      'name' => 'date_of_birth',
      'type' => 'date',
      'label' => 'Geburtsdatum',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
      ],
    ],
    6 => [
      'name' => 'place_of_death',
      'type' => 'text',
      'label' => 'Sterbeort',
      'info' => '',
      'group' => 'Person_Ort',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    7 => [
      'name' => 'date_of_death',
      'type' => 'date',
      'label' => 'Sterbedatum',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
      ],
    ],
    8 => [
      'name' => 'nationality',
      'type' => 'text',
      'label' => 'Nationalität',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    9 => [
      'name' => 'last_place_of_residence',
      'type' => 'text',
      'label' => 'Letzter Wohnort',
      'info' => '',
      'group' => 'Person_Ort',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    10 => [
      'name' => 'marriage',
      'type' => 'contentItemLink',
      'label' => 'Ehe',
      'info' => '',
      'group' => 'Referenz',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'link' => 'person',
        'filter' => NULL,
        'display' => NULL,
      ],
    ],
    11 => [
      'name' => 'father',
      'type' => 'contentItemLink',
      'label' => 'Vater',
      'info' => '',
      'group' => 'Referenz',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'filter' => NULL,
        'link' => 'person',
        'display' => NULL,
      ],
    ],
    12 => [
      'name' => 'mother',
      'type' => 'contentItemLink',
      'label' => 'Mutter',
      'info' => '',
      'group' => 'Referenz',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'filter' => NULL,
        'link' => 'person',
        'display' => NULL,
      ],
    ],
    13 => [
      'name' => 'religion',
      'type' => 'text',
      'label' => 'Religion',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
    14 => [
      'name' => 'profession',
      'type' => 'text',
      'label' => 'Beruf',
      'info' => '',
      'group' => 'Person_Info',
      'i18n' => false,
      'required' => false,
      'multiple' => false,
      'meta' => [
      ],
      'opts' => [
        'multiline' => false,
        'showCount' => true,
        'readonly' => false,
        'placeholder' => NULL,
        'minlength' => NULL,
        'maxlength' => NULL,
        'list' => NULL,
      ],
    ],
  ],
  'preview' => [
  ],
  'group' => 'Person',
  'meta' => NULL,
  '_created' => 1764672419,
  '_modified' => 1764674773,
  'color' => NULL,
  'revisions' => false,
];