name: Linter (Frontend)

on: 
  push:
    branches: [dev]
  pull_request:
    types: [opened, edited, ready_for_review]

permissions: 
    checks: write
    contents: write

jobs:
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
        - name: Check out Git repository
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 22
        
        - name: Install Node.js dependencies
          run: |
            cd frontend
            npm install
            npm ci

        - name: Run linters
          uses: wearerequired/lint-action@v2
          with:
            eslint: true
            eslint_dir: frontend/